services:
  - type: web
    name: gestor-rede-social
    env: python
    buildCommand: |
      mkdir -p static templates
      pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        value: postgresql://gestor_rede_social_database_user:Hc6I4oI9guqI8Lv1oV2GR6al70t0yAHj@dpg-ctese6lds78s73dk0i8g-a.frankfurt-postgres.render.com/gestor_rede_social_database
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"